added steps to check items count inside a folder
owncloud/owncloud-test-middleware pull request #100
Opened 2022-02-11 10:27 UTC by sushmita56

added a step to check no. of items inside the provided folder

2022-02-11 11:28 UTC, kiranparajuli589 requested changes
also please revert all other changes which are not related

2022-02-11 11:28 UTC, kiranparajuli589 commented on src/stepDefinitions/filesContext.js
> +)
hmm...implementations are ditto.
you can avoid duplications like:
```suggestion
Then(
  'as user {string} folder {string} should contain {string} items',
  async function (userName, folderName, itemsCount) {
    const davPath = webdavHelper.createDavPath(userName, folderName)
    const resourcesInsideFolder = await webdavHelper.propfind(davPath, userName, [])
    let jsonResponse = convert.xml2json(resourcesInsideFolder)
    jsonResponse = JSON.parse(jsonResponse)
    let actualCount = jsonResponse.elements[0].elements.length
    actualCount = actualCount - 1
    return assert.strictEqual(
      actualCount,
      parseInt(itemsCount),
      `Expected ${folder_count} items inside ${folderName} but found ${actualCount}`
    )
  }
)
```

2022-02-11 12:05 UTC, Talank reviewed
use const instead of var while loading modules.

2022-02-11 12:05 UTC, Talank commented on src/stepDefinitions/filesContext.js
> +var util = require('util')
```suggestion
const util = require('util')
```

2022-02-11 12:05 UTC, Talank commented on src/stepDefinitions/filesContext.js
> +var convert = require('xml-js')
```suggestion
const convert = require('xml-js')
```

2022-02-14 06:35 UTC, saw-jan requested changes
@sushmita56 you can undo these format changes for now and only add what you need in this PR.
We need to fix those unformatted files though.

2022-02-14 09:30 UTC, saw-jan requested changes
Some changes request

2022-02-14 09:30 UTC, saw-jan commented on src/stepDefinitions/filesContext.js
>  const createdFiles = []
just to group
```suggestion
const webdavHelper = require("../helpers/webdavHelper")
const convert = require('xml-js')

const createdFiles = []
```

2022-02-14 09:30 UTC, saw-jan commented on src/stepDefinitions/filesContext.js
> +  actualCount = actualCount - 1
`xml-js` comes with `xml2js` function so you can directly convert XML to js object.
```suggestion
  const xmlResponse = await webdavHelper.propfind(davPath, userName, [])
  const resObj = convert.xml2js(xmlResponse)
  // also add some comment here why we need to subtract by 1
  const actualCount = resObj.elements[0].elements.length - 1
```

2022-02-14 09:30 UTC, saw-jan commented on src/stepDefinitions/filesContext.js
> +    `Test Failed...Expected ${itemsCount} folders but got ${actualCount}`
```suggestion
    `Expected '${itemsCount}' items inside the folder '${folderName}' but got '${actualCount}'`
```

2022-02-14 11:04 UTC, kiranparajuli589 commented on src/stepDefinitions/filesContext.js
> +  actualCount = actualCount - 1
why subtract? please add a comment about this.

2022-02-15 04:04 UTC, Talank commented on src/stepDefinitions/filesContext.js
> +  let actualCount = jsonResponse.elements[0].elements.length
`jsonResponse.elements[0].elements.length` does not give much of the information to the reader. Can you add a comment on this line as well? Which element that you are targeting?

2022-02-15 04:35 UTC, saw-jan approved these changes
LGTM

2022-02-15 04:58 UTC, kiranparajuli589 approved these changes

2022-02-15 04:59 UTC, merged

2022-02-15 06:41 UTC, phil-davis commented on src/stepDefinitions/filesContext.js
> +    // so we need to subtract 1 to get the acutal items count
Typo fixed in PR #102